"""add uq const

Revision ID: 2e6f01f33ed7
Revises: ae48063fa186
Create Date: 2023-07-06 14:37:24.294114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6f01f33ed7'
down_revision = 'ae48063fa186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_title', ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_title', type_='unique')

    # ### end Alembic commands ###
