"""add password_hash

Revision ID: 73391897dda6
Revises: a289d9cbb861
Create Date: 2023-07-07 14:37:20.511212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73391897dda6'
down_revision = 'a289d9cbb861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
